version: "3.8"

services:
  sba:
    image: adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine
    ports:
      - 8000:8000
      - 8080:8080
    expose:
      - "8000"
    depends_on:
      - sql
    networks:
      - app-net
    volumes:
      - ./jarFile/projectWork-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -jar /app/app.jar

  sql:
    image: mysql
    ports:
      - 3306:3306
    networks:
      - app-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./dbInit:/docker-entrypoint-initdb.d

  website:
    image: httpd
    ports:
      - 80:80
    networks:
      - app-net
    volumes:
      - ./html:/usr/local/apache2/htdocs
      
networks:
  app-net:
    driver: 
      "bridge"